name: Build

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PORT: ${{ secrets.PORT }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
      DEBUG: ${{ secrets.DEBUG }}

    steps:
      - name: Setup Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: make build

      - name: Run Server
        run: |
          ./main &
          sleep 30

      - name: Send Request
        run: |
          API_URL="http://127.0.0.1:${{ secrets.PORT }}/api/v1/health"
          STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}" $API_URL)
          if [ "$STATUS_CODE" -eq 200 ]; then
            echo "API is deployed and responding with status code 200 (OK)"
          else
            echo "Error: API deployment failed. Received status code: $STATUS_CODE"
            exit 1
          fi
