name: Lint, and Format

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master

jobs:
  lint-format:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'

      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64

      - name: Run gofmt
        run: |
          gofmt -l .
          if [ $? -eq 0 ]; then
            echo "Formatting completed successfully."
          else
            echo "Formatting encountered an error."
            exit 1
          fi
